name: at_find_api
description: A readonly webapp for searching for public @ protocol information
homepage: https://www.atsign.com
documentation: https://github.com/atsign-company/at_find_api
repository: https://github.com/atsign-company/at_find_api

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http_server: ^0.9.6
  at_lookup:
    git:
      url: git@github.com:atsign-company/atsign_foundation.git
      path: at_lookup
      ref: dev_env
  base2e15: ^0.3.0

dev_dependencies:
  # Adding test_cov for generating the test coverage.
  test_cov: ^0.2.1
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: any
  build_web_compilers: any
